### ISSUE TITLE
encryption - 1.1

### ISSUE THREAD

**Issue by Wixonic** [Wix-Corp/Time#1]
# Time.encrypt()

A function that will encrypt the text passed as a parameter.

- Support for most of the characters  **UTF-8**
- **Only one** parameter if is possible

# Time.decrypt()

The same function as `Time.encrypt()` but reversed.

***

[encryption.js](https://github.com/Wixonic/Time/blob/master/%E2%9A%92/1.1/encryption.js)

**Comment by Klevh** [comment]
I am working on translating this code
https://github.com/Klevh/CCypher/blob/master/crypt.c

**Comment by Wixonic** [comment]
> I am working on translating this code
> 
> https://github.com/Klevh/CCypher/blob/master/crypt.c

**Thanks @Klevh ** !!

**Comment by Klevh** [comment]
https://code.sololearn.com/WiUtR2E9VHY0/?ref=app
